describe('Thrive Automator Tests', () => {
  beforeEach(() => {
      cy.session('todos', () => {
        cy.visit('/wp-login.php')
        cy.get('#user_login')
          .clear()
          .type('admin')
          .should('have.value', 'admin')
        cy.get('#user_pass')
          .type('baiyufJY%DZbZ0SWadiIp@1!')
        cy.get('#wp-submit').click()
        cy.url().should('include', '/wp-admin')
        cy.visit('/wp-admin/admin.php?page=thrive_automator')
        cy.get('.tap-button').click()
        cy.get('.tap-app-wordpress').click()
        cy.get('.tap-toggle-content > :nth-child(2)').click()
        cy.get('.tap-button--upper').click()
        cy.get('.last-step').click()
        cy.get('.tap-app-wordpress').click()
        cy.get('.tap-toggle-content > :nth-child(1)').click()
        cy.get('.tap-fw > .tap-search-input > .no-value').click()
        cy.get('[data-item-index="2"] > .tap-fw').click()
        cy.get('.tap-button--upper').click()
        cy.get('.tap-inline-input-container > span').click()
        cy.get('.tap-inline-input-container').clear()
          .type('demo aut 1')
        cy.get('.tap-aut-status > .tap-button--ghost').click()
        cy.get('.tap-button--save').click()
        cy.contains('Add new').click()
        cy.get('.tap-app-wordpress').click()
        cy.get('.tap-toggle-content > :nth-child(2)').click()
        cy.get('.tap-button--upper').click()
        cy.get('.last-step').click()
        cy.get('.tap-app-wordpress').click()
        cy.get('.tap-toggle-content > :nth-child(1)').click()
        cy.get('.tap-fw > .tap-search-input > .no-value').click()
        cy.get('[data-item-index="2"] > .tap-fw').click()
        cy.get('.tap-button--upper').click()
        cy.get('.tap-inline-input-container > span').click()
        cy.get('.tap-inline-input-container').clear()
          .type('demo aut 2')
        cy.get('.tap-aut-status > .tap-button--ghost').click()
        cy.get('.tap-button--save').click()

      })

// bulk actions: activate, deactivate, delete-Cancel, delete-Yes

 it('bulk action: deactivate all automations', () => {
    cy.visit('/wp-admin/admin.php?page=thrive_automator')
    cy.get('.tap-checkmark').first().click()
    cy.get(':nth-child(3) > .tap-icon-wrapper > .tap-icon').click()
    cy.get('.tap-filter-publish > .tap-filter-item-number').should('have.text', 0)
  })
  it('bulk action: activate all automations', () => {
      cy.visit('/wp-admin/admin.php?page=thrive_automator')
      cy.get('.tap-filter-active > .tap-filter-item-number')
        .invoke('text')
        .then((text1) => {
          cy.get('.tap-checkmark').first().click()
          cy.get('.tap-icon-rocket').click()
          cy.get('.tap-filter-publish > .tap-filter-item-number')
            .invoke('text')
            .should((text2) => {
              expect(text1).eq(text2)
            })
        })
    })
    it('bulk action: delete all automations No, cancel', () => {
      cy.visit('/wp-admin/admin.php?page=thrive_automator')
      cy.get('.tap-filter-active > .tap-filter-item-number')
        .invoke('text')
        .then((text1) => {
          cy.get('.tap-saved-actions > :nth-child(1) > .tap-checkbox-wrapper > .tap-checkmark').click()
          cy.get(':nth-child(4) > .tap-icon-wrapper > .tap-icon').click()
          cy.get('.tap-button--grey').click()
          cy.get('.tap-filter-active > .tap-filter-item-number')
            .invoke('text')
            .should((text2) => {
              expect(text1).eq(text2)
            })
        })
    })
    it('bulk action: delete all automations Yes, delete', () => {
      cy.visit('/wp-admin/admin.php?page=thrive_automator')
      cy.get('.tap-saved-actions > :nth-child(1) > .tap-checkbox-wrapper > .tap-checkmark').click()
      cy.get(':nth-child(4) > .tap-icon-wrapper > .tap-icon').click()
      cy.get('.tap-button--delete').click()
      cy.get('.tap-no-automations-content').should('be.visible')
    })
   })